DEFAULT_PATH = "/mnt/d/DOCR/OUCRU-Handwriting-Pipeline"
PAPERDETCTION_FOLDER_SUFFIX = '/PaperDetection'
PREPROCESSING_FOLDER_SUFFIX = '/Preprocessing'
TEXTDETECRION_FOLDER_SUFFIX = '/TextDetection'
INPUT_SUFFIX = '/Input'
OUTPUT_SUFFIX = '/Output'
ANNOTATED_OUTPUT_SUFFIX = '/Annotated_Output'